### ISSUE TITLE
PoseC3D configuration about SlowFast network

### ISSUE THREAD

**Issue by shenjiyuan123** [kennymckormick/pyskl#1]
Hi, it's really an amazing job! I really like it. But I didn't find the config about using SlowFast network (there is only SlowOnly network configuration). So could you offer a script about that? Thank you so much!

**Comment by shenjiyuan123** [comment]
That's so great! Thank you very much!

**Comment by liu-bill666** [comment]
I also wang to know how to integrate the classification results of video and pose. Is it just a simple weighted average of their scores？

**Comment by Haoran-Qi** [comment]
are there any updates? 
![image](https://user-images.githubusercontent.com/13559152/185237200-0a882c95-bba5-489f-b048-2499904f0e0d.png)

**Comment by taliegemen** [comment]
I am also interested, and I will try to make changes in the config file to make it like resnetslowfast. If I get lucky I will also share my config here.

**Comment by Xinxinatg** [comment]
@taliegemen Hi I am just wondering have you been able to implement the fusion of pose and rgb?

**Comment by taliegemen** [comment]
Hello,
Instead of implementing it i am now trying to maybe improve the backbone for recognition, or changing it with ResnetSlowFast. I think it should be easy to change it to ResnetSlowFast after looking at the code a little bit.
I think even if we use pose and rgb together we can not get much improvement, thats why i did not try to do it.

**Comment by kennymckormick** [comment]
Finally, I have implemented RGBPoseConv3D in PYSKL 🤣 . The implementation is in PR #116 and has been merged to the main branch.
