### ISSUE TITLE
have a question about gesture demo?

### ISSUE THREAD

**Issue by zhanght021** [kennymckormick/pyskl#141]
Hello, I have a question about the gesture demo. As you said, for skeleton-based gesture recognition, currently you adopted a light variant of stgcn++ trained on the HaGRID gesture recognition dataset. But the HaGRID is a static image dataset, so how did you train the stgcn++ model on HaGRID datasets? Only repeating the image to form a video clip ?

**Comment by kennymckormick** [comment]
Yes, I just inflate a static frame in temporal to form the video clip 🤣 You may find it sounds weird. The motivation is, I want to use a single model to handle the static gestures (from HaGRID) and dynamic gestures (from Jester). However, when I'm making the demo I find that the visualization effect of dynamic gestures is poor (due to the poor visual quality of Jester and the short time span of the dynamic gestures). Thus I only keep the static gestures in my final demo.
